# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gradient0 <- function(P_, scrutinA, scrutinB) {
    .Call(`_anelex_gradient0`, P_, scrutinA, scrutinB)
}

gradient <- function(P_, scrutinA, scrutinB, nThreads = 2L) {
    .Call(`_anelex_gradient`, P_, scrutinA, scrutinB, nThreads)
}

gradient2 <- function(P_, scrutinA, scrutinB, nThreads = 2L) {
    .Call(`_anelex_gradient2`, P_, scrutinA, scrutinB, nThreads)
}

likelihood <- function(P_, scrutinA, scrutinB, nThreads = 2L) {
    .Call(`_anelex_likelihood`, P_, scrutinA, scrutinB, nThreads)
}

likelihood2 <- function(P_, scrutinA, scrutinB, nThreads = 2L) {
    .Call(`_anelex_likelihood2`, P_, scrutinA, scrutinB, nThreads)
}

